### ISSUE TITLE
LOl

### ISSUE THREAD

**Issue by AlexandriteErikParacelsus** [ErikParacelsus/Issues-testing#2]
@LegitSoulja can you post the link of the client files here, after i download it you can remove the link.

**Comment by segg21** [comment]
You really need it? Like when? Cause I'm afk atm, currently using my phone.

**Comment by AlexandriteErikParacelsus** [comment]
Yes i really need it like REALLY REALLY BAD

**Comment by segg21** [comment]
When do you need it??

**Comment by AlexandriteErikParacelsus** [comment]
@LegitSoulja When you're ready

**Comment by LegitSoulja** [comment]
@ErikParacelsus sorry, im been really busy lately, and i have not see a notification from you.
[Agarioclient.zip](https://github.com/ErikParacelsus/Issues-testing/files/273148/Agarioclient.zip)

**Comment by AlexandriteErikParacelsus** [comment]
ok

**Comment by AlexandriteErikParacelsus** [comment]
@LegitSoulja w8 u wot i cant download that

**Comment by segg21** [comment]
You was too late to download? I heard private servers are now back

**Comment by AlexandriteErikParacelsus** [comment]
I know but are we need client?

**Comment by segg21** [comment]
Yup. They didn't bring them back yet :/. They say they did.. I tested & nothing
